title: Avans Farm
author: Travis Dailey
subtitle: 
description: 

email: travismdailey@gmail.com
pinterest: 
facebook: avansfarm
google: 115756377219105248824
knot: /Vendors/Avans-Farm-Weddings/Profile/CAR/190/612682/profile


source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']

permalink: /:categories/:title
markdown: rdiscount

safe:        true
watch:       false    # deprecated
server:      false    # deprecated
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false